### ISSUE TITLE
V3 Template Cart Tracking Issue

### ISSUE THREAD

**Issue by rahul-snowplow** [snowplow/snowplow-gtm-tag-template-v3#24] opened 2023-06-06 08:45 UTC
Hi Team,

I have created a new tag of type - Cart Tracking and I am passing all the required fields as well.
I am passing static values as per the screenshot 
![image](https://github.com/snowplow/snowplow-gtm-tag-template-v3/assets/85717917/f1723fa1-e607-4e62-92d3-4302565424e9)

The event fails and complains about `unitPrice` and `quantity` being string but I am passing `integer` against it.
Do I have to convert the values into `int` first and then pass them as parameter values?

**Comment by adatzer** [comment] 2023-06-21 10:04
Hi @rahul-snowplow !
Indeed, according to the schema these values need to be numbers. Since the text-box in GTM UI returns strings, you'd indeed need to pass those values through variables evaluating to the right type.

At the moment the tag does not make any type casting in code, probably because we assume that for most use cases, passing the values through variables is expected. 
Do you think this is ok?

**Comment by adatzer** [comment] 2024-03-04 18:14
Closing, as this is expected behaviour.

**Closed by adatzer** 2024-03-04 18:14 UTC
